### ISSUE TITLE
cppman fails to download some pages

### ISSUE THREAD

**Issue by mar04** [aitjcize/cppman#10]
2351 manual pages cahced successfully.
5 manual pages failed to cache.

ios
Input/Output
istream
ostream
iostream

Using ArchLinux and package from AUR.
Also fix spelling cahced -> cached ;)

**Comment by Zopieux** [comment]
There are still issues with some of these pages and others.
```
Caching <atomic> ...
Retrying ...
Retrying ...
Retrying ...
Error caching <atomic> ...
```

And then:
```
$ cppman '<atomic>'
error: list index out of range
```

**But also**:
```
Caching std::basic_fstream::operator= ...
Retrying ...
Retrying ...
Retrying ...
Error caching std::basic_fstream::operator= ...
```

And then:
```
$ cppman 'std::basic_fstream::operator='
# works great
```
So I'm not sure what is happening here. I guess the failed pages that worked manually were just failed because of temporary network issues. For `<atomic>` and `<iterator>`, these are really broken.

**Comment by Yanpas** [comment]
Fails to download `operator/`

**Comment by XPCX** [comment]
I've tried several times with the version found by pip, the Debian repo, etc., and it keeps failing to cache or download on-demand. ("Retrying..." x 3 for every item.) Switching sources did not help. Adding root privileges to the cache-all command allowed most of the requests to succeed. (<atomic>, Input/Output, and <iterator> were among the failures.) I don't remember anything but the original installation needing privileges, but I could be mistaken. I'll post again if I can figure anything out.

**Comment by aitjcize** [comment]
@XPCX the pages you mentioned should be fixed in the latest release.
