### ISSUE TITLE
cppman: error: no such option: -s

### ISSUE THREAD

**Issue by GasparVardanyan** [aitjcize/cppman#104]
Supports two backends (switch it with cppman -s):
cplusplus.com
cppreference.com

┌─[gaspar@GasparVardanyan]─[~]
└──╼ $ cppman -s
Usage: cppman [OPTION...] PAGE...

cppman: error: no such option: -s

**Comment by SGSSGene** [comment]
Hi, Thank you for your report.

The output of `cppman -s` should be
```
Usage: cppman [OPTION...] PAGE...

cppman: error: -s option requires 1 argument
```
Can you post following information:
1. `cppman --version`
2. Which OS are you using?
3. How did you install it? (pip, apt-get, from git)

Thank you

**Comment by GasparVardanyan** [comment]
Hi!
**1)**
**$ cppman --version**
/sbin/cppman Ver 0.3.1
Copyright (C) 2010 Wei-Ning Huang
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Wei-Ning Huang (AZ) <aitjcize@gmail.com>



**2)**

Arch Linux (BlackArch)

**$ uname -r**
5.1.12-arch1-1-ARCH



**3)**

Package manager: pacman

Installation command: pacman -S cppman

Package information:

**$ pacman -Si cppman** 
Repository      : blackarch
Name            : cppman
Version         : 0.3.1-1
Description     : manual page formatter that generates C++ man pages from
                  cplusplus.com
Architecture    : any
URL             : https://github.com/aitjcize/cppman
Licenses        : GPL
Groups          : None
Provides        : None
Depends On      : python2  vim  groff
Optional Deps   : None
Conflicts With  : cppman-git
Replaces        : None
Download Size   : 85.41 KiB
Installed Size  : 515.00 KiB
Packager        : Evan Teitelman <teitelmanevan@gmail.com>
Build Date      : Sun 06 Apr 2014 03:41:40 PM +04
Validated By    : MD5 Sum  SHA-256 Sum  Signature

**Comment by SGSSGene** [comment]
Hi, You have an old version of cppman installed. Newest version is 0.5.0

You could try to remove cppman and install it via `pip install cppman`
