### ISSUE TITLE
cppman to support C APIs from cppreference.com

### ISSUE THREAD

**Issue by laoshaw** [aitjcize/cppman#117]
currently when I do `cppman strcpy` it will show c++ content for strcpy, there is a lot C-only html pages on the site, can cppman let me access those pages(I'm a c programmer) instead of c++-based c headers/APIs?

**Comment by aitjcize** [comment]
For C man pages, you should just use your system man command, i.e. `man 3 strcpy`

**Comment by jxu** [comment]
but the cppreference pages provide useful additional info.
