### ISSUE TITLE
Indexing issues: syntax error and incompatibility with python 3.9

### ISSUE THREAD

**Issue by ecogest** [aitjcize/cppman#120]
Hello,

First, thanks for this program which looks amazing in nvim.

Still, I encountered a few issues with `cppman -r`:
- The easiest to fix is that indexing is broken by python 3.9 since `threading.Thread` 's method `isAlive()` has been renamed to `is_alive()`. (error message: "error: 'Thread' object has no attribute 'isAlive'") -> file: crawler.py, l.91
-  The second issue, with an older version of python (in my case I used python 3.8.6), that I get a `error: near "(": syntax error` at the end of indexing (I tried both cppreference.com and cplusplus.com). No idea why.
- Hence with the default database (since I can't rebuild the index), I can't find some very basic pages of cppreference like https://en.cppreference.com/w/cpp/string/basic_string/getline (I can only get https://en.cppreference.com/w/cpp/io/basic_istream/getline)

I am on debian 10, I tried installing cppman via pip and brew (never managed to make the indexing work properly, and debian repo's cppman does not support nvim). 

Regards.

**Comment by aitjcize** [comment]
Reopen for bullet 3

**Comment by aitjcize** [comment]
Fixed in 0.5.2
