### ISSUE TITLE
cppman -r broken

### ISSUE THREAD

**Issue by laoshaw** [aitjcize/cppman#126]
it will quit python  and also corrupt the existing index db

**Comment by ton** [comment]
I get this on the command-line:

```
10:27:19|ton@ash:~/dev/fractal/repos/fractal/src 󰘬 ipdelta$ cppman -r
Indexing 'http://www.cplusplus.com/reference/' (depth 1)...
error: 'Thread' object has no attribute 'isAlive'
```

**Comment by aitjcize** [comment]
@ton I believe you are using an older release. Please try the latest version.

Just tested the master branch it's working just fine.

**Comment by ton** [comment]
@aitjcize yes, indeed, I was using 0.5.1 from AUR, just tested with 0.5.3 and it works correctly. Thanks!
