### ISSUE TITLE
cppman -m true not work

### ISSUE THREAD

**Issue by zdmgmail** [aitjcize/cppman#127]
system: 5.12.12-arch1-1

use 
```
pip install cppman
cppman -c
cppman -m true
```

then `cppman cout` work ok, but `man cout` get `no manual entry for cout`

man cppman get 
```
   man compatibility
       cppman   automatically   adds  '$XDG_CACHE_HOME/cppman/man'  to
       '~/.manpath', so the cached man pages can also be  viewed  with
       'man'  command. Note that to view uncached man pages, you still
       need to run 'cppman'.
```

In `$XDG_CACHE_HOME/cppman/man` have 

```
cppreference.com
man3
manindex(empty)
```

and `~/.manpath` not exist

**Comment by matu3ba** [comment]
Related strace [strace_cppmanInstall.log](https://github.com/aitjcize/cppman/files/6951404/strace_cppmanInstall.log)
from running `strace cppman -m true &> strace_cppmanInstall.log`.

@zdmgmail Looks like along
````python
        config.UpdateManPath = config.parse_bool(options.mandb)
        update_mandb_path()
        update_man3_link()
```
is broken without `~/.manpath`.

**Comment by zdmgmail** [comment]
``` 
touch ~/.manpath
mandb 
```
then work ok
