### ISSUE TITLE
`error: no such table: cppreference.com_keywords` when database was created by old cppman

### ISSUE THREAD

**Issue by czchen** [aitjcize/cppman#138]
Originally from <https://bugs.debian.org/995477>.

When database was created by old cppman, there is no `${source}_keywords` table, and there is no mechanism to trigger rebuild automatically. Because of this, `cppman` always shows `error: no such table: cppreference.com_keywords` error.

**Comment by aitjcize** [comment]
Thanks for reporting. Most users does not index the entries themselves so the `index.db` file should be from the package manager and this should not happen.

We can add logic in code to detect old database and prompt user for deleting the old database.

**Comment by baziorek** [comment]
I just installed `cppman` and faced the same problem.
I tried:
```
cppman vector
cppman std::vector
cppman std::vector::begin
cppman 'vector::begin'
```
and always the same problem.
I also checked two sources:
```
cppman -s 'cplusplus.com'
cppman -s cppreference.com
```
My version is:
```
cppman -v     
/bin/cppman Ver 0.5.3
```
I've just installed with:
```
sudo apt-get install cppman
```

**Comment by aitjcize** [comment]
Version 0.5.3 on debian is bundled with a bad `index.db` for some reason. Please upgrade to the latest version.
You can install it with `pip install cppman`

**Comment by baziorek** [comment]
> Version 0.5.3 on debian is bundled with a bad `index.db` for some reason. Please upgrade to the latest version. You can install it with `pip install cppman`

Thanks, it worked!
