### ISSUE TITLE
gzip: stdout: Broken pipe

### ISSUE THREAD

**Issue by madskjeldgaard** [aitjcize/cppman#144]
Hi, all of a sudden I started getting broken pipe errors:
```
/opt/homebrew/bin/cppman Ver 0.5.4
Copyright (C) 2010 Wei-Ning Huang
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Wei-Ning Huang (AZ) <aitjcize@gmail.com>.
```
From this command for example:

```bash
 cppman std::list

gzip: stdout: Broken pipe
```

I'm on  MacOS 13.0.1 (22A400) on an M2 macbook

**Comment by kanewjp** [comment]
Same issue on M1 pro

**Comment by vbaswin** [comment]
>```
>gunzip: error writing to output: Broken pipe
>gunzip: /Users/aswinvb/.cache/cppman/cppreference.com/std::vector<T,Allocator>::begin
>std::vector<T,Allocator>::cbegin.3.gz: uncompress failed
>```

on m2 macbook air

**Comment by aitjcize** [comment]
You need to install the `groff` command, it's part of the dependencies.

`brew install groff`

**Comment by madskjeldgaard** [comment]
> You need to install the `groff` command, it's part of the dependencies.
> 
> `brew install groff`

This fixes it, but it's actually not part of the dependencies on homebrew at least: https://formulae.brew.sh/formula/cppman#default

**Comment by aitjcize** [comment]
I guess I can send a PR for the brew formula.

**Comment by madskjeldgaard** [comment]
Thanks! Maybe also there should be an addition to the README about this dependency? Thanks a lot. really happy it is working again, I'm a big fan of this tool :)

**Comment by glenvt18** [comment]
Hi. Is `agroff` a MacOS-specific thing or is it a typo? There is no `agroff` on Linux and after 9adce61 cppman is broken on Linux.

**Comment by aitjcize** [comment]
@glenvt18 sorry that was indeed a typo. Fixed on master.

**Comment by madskjeldgaard** [comment]
I'm closing this now as it seems to work fine (for me at least) now. Thanks for the fixes @aitjcize
