### ISSUE TITLE
Install groff 

### ISSUE THREAD

**Issue by obemu** [aitjcize/cppman#146]
The pager.sh script uses groff when piping a archived page into the selected pager.

Not havin the package "groff" installed on your machine causes this process to fail with the error message:
"gzip: stdout: Broken pip".

Possible solution:
Maybe check in pager.sh if groff is installed ?

**Comment by aitjcize** [comment]
This as been addressed in https://github.com/aitjcize/cppman/commit/9adce61e0aa18a10011994c1b028190e86421b78
