### ISSUE TITLE
HTTP Error 403

### ISSUE THREAD

**Issue by BoManev** [aitjcize/cppman#150]
- Ubuntu 22.04
- Python 3.10.6
- pip 23.0.1
- cppman 0.5.5

I've installed cppman using pip3.
When I use cppreference, I get the following error:
`error: HTTP Error 403: Forbidden`.
However, when I use cplusplus, there's no error.
I can ping both cppreference and cplusplus.

**Comment by glenvt18** [comment]
@BoManev You can try #149
