### ISSUE TITLE
Highlighting fails with vim and less

### ISSUE THREAD

**Issue by arminveres** [aitjcize/cppman#155]
Highlighting fails, as it the pager only prints escape sequences
![2023-05-10_13-50](https://github.com/aitjcize/cppman/assets/45210978/514b5b27-bfd7-4a33-953f-36020673fc7b)

I tried using vim, less as pager. 
I was also wondering, whether bat worked, but I cannot set it as pager.
Neovim works, but I needed to disable a plugin, otherwise it would dump a hex version of it and since the buffer is not modifiable I had to remove [that plugin](https://github.com/RaafatTurki/hex.nvim).

Following version is installed
```
/home/arminveres/.local/bin/cppman Ver 0.5.6
Copyright (C) 2010 Wei-Ning Huang
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Wei-Ning Huang (AZ) <aitjcize@gmail.com>.
```

**Comment by KSR-Yasuda** [comment]
As for `less`, [this](https://github.com/aitjcize/cppman/pull/168) would fix it.

**Comment by aitjcize** [comment]
Thanks @KSR-Yasuda, marking this one as fixed.
