### ISSUE TITLE
error: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by alexpanter** [aitjcize/cppman#159]
As the title says. Steps to retrace:

1) Machine with Ubuntu 23
2) Install `cppman` through `apt`
3) Try something like `cppman std::map` to get the error.

Now I'm not exactly a networking expert. Usually I would think that port 443 is for HTTPS-connections, and that somehow Ubuntu has a firewall preventing that, but there could be other reasons - and I'm not really sure.

Is there a "desired" way to circumvent this problem, e.g. change port number, or set up a local proxy with HTTPS (is that even possible?), or something else?

In advance, thank you!

**Comment by megaproes** [comment]
same error

**Comment by aitjcize** [comment]
This is a dup of #150, please install via pip instead.
