### ISSUE TITLE
[BUG] cannot use

### ISSUE THREAD

**Issue by Ruizhi-Deng** [aitjcize/cppman#166]
when I use cppman, for expamle, `cppman std::cin` or `cppman -c`, it reports `error: no such table: cplusplus.com_keywords` and I've tried changing the source but it doesn't help.

**Comment by AeonJh** [comment]
You can update you cppman version 0.5.4 or later (Originally from https://bugs.debian.org/995477). Or using cppman -r to rebuild the index-database. The second way may take a lot of time.

**Comment by aitjcize** [comment]
Please update your installation to latest.
