### ISSUE TITLE
Empty pages opened in vim

### ISSUE THREAD

**Issue by alkhatib** [aitjcize/cppman#32]
- New install using 'sudo pip install cppman'
- cppman -v
  `/usr/local/bin/cppman Ver 0.4.0
  Copyright (C) 2010 Wei-Ning Huang
  License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
  This is free software: you are free to change and redistribute it.
  There is NO WARRANTY, to the extent permitted by law.`
- cppman std::vector

Result is an empty buffer open in vim.
- Changed pager to less and system, same result.
- Tried rebuilding index

**Comment by tianxingyzxq** [comment]
I have the same problem. 
cppman -v
Copyright (C) 2010 Wei-Ning Huang
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

I have tried pip and apt-get, the result is same. can anyone help?

**Comment by SGSSGene** [comment]
Duplicate of #103 right?
