### ISSUE TITLE
Update debian package version to 4.2

### ISSUE THREAD

**Issue by aitjcize** [aitjcize/cppman#34]
Hi @czchen,
I've just released 0.4.2 version, can you help update the package version?
Thanks!

**Comment by czchen** [comment]
@aitjcize 

Currently [Debian is in freeze for Jessie](https://release.debian.org/jessie/freeze_policy.html), so I cannot upload for Jessie right now. I will do it for next Debian version.

**Comment by aitjcize** [comment]
Thanks a lot!

**Comment by czchen** [comment]
Just put the 0.4.2 into experimental branch. Will merge to unstable/testing when Jessie has released.

**Comment by aitjcize** [comment]
Thanks!
