### ISSUE TITLE
make it work with offline version

### ISSUE THREAD

**Issue by agauniyal** [aitjcize/cppman#38]
Is there a way to point cppman to an offline version of cppreference locally? 
You can download offline archives via here : http://en.cppreference.com/w/Cppreference:Archives 
so that I don't have to cache all pages , and it works offline too.

**Comment by aitjcize** [comment]
I already have plan for this, thanks :)

**Comment by agauniyal** [comment]
Is this being worked on? Caching takes much more time than downloading a resource :/ and often fails.

**Comment by aitjcize** [comment]
I'll work on it this weekend, but you are welcome to contribute :)

**Comment by agauniyal** [comment]
Any progress :/

**Comment by mid-kid** [comment]
Any update?
