### ISSUE TITLE
cppman failed in python 3.3

### ISSUE THREAD

**Issue by BrytonLee** [aitjcize/cppman#39]
cppman is not compatibility with python 3.3, there are two man issuses:
1. print is function in python 3.3.
2. **except XXError, e:** and **except (XXError, YYError), e:** should be change to **except XXError as  e:** **except (XXError, YYError) as e:**

**Comment by aitjcize** [comment]
Thanks, I've plans to port cppman to python 3 soon. You are welcome to help :)

**Comment by czchen** [comment]
I am working on it in https://github.com/czchen/cppman/tree/feature/python3. It still has problem in relative import.

**Comment by aitjcize** [comment]
Thanks! I've also tried several attempt on this, but there seems to be a lot of problem regard to the difference in python3 buf and str.

**Comment by czchen** [comment]
I sent a PR for python3 in [here](https://github.com/aitjcize/cppman/pull/40), please help to test it. Maybe it shall be merged to another branch first and let other to test it before merging to master.

**Comment by aitjcize** [comment]
Yes I already tried it. Let me comment on that PR.

**Comment by aitjcize** [comment]
Fixed
