### ISSUE TITLE
`q` does not quit

### ISSUE THREAD

**Issue by egarrulo** [aitjcize/cppman#44]
Pressing `q` does not quit `cppman` as in `man`.  Instead, the command `:q!<CR>` appears at the bottom of the screen.  To quit, you must delete the `<CR>` part and press Enter.  Tested with:
- cppman 0.4.5
- vim 7.4

Thanks for your attention.

**Comment by aitjcize** [comment]
<CR> actually means enter in vim. It worked on my vim 7.4 though. Can you show me your ```vim --version``` output?

**Comment by egarrulo** [comment]
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 25 2015 12:20:44)
    Compiled by egarrulo@debian
    Normal version with GTK2 GUI.  Features included (+) or not (-):
    -arabic          +file_in_path    -mouse_sgr       +tag_binary
    +autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
    +balloon_eval    +float           -mouse_urxvt     -tag_any_white
    +browse          +folding         +mouse_xterm     -tcl
    +builtin_terms   -footer          +multi_byte      +terminfo
    +byte_offset     +fork()          +multi_lang      +termresponse
    +cindent         +gettext         -mzscheme        +textobjects
    +clientserver    -hangul_input    +netbeans_intg   +title
    +clipboard       +iconv           +path_extra      +toolbar
    +cmdline_compl   +insert_expand   -perl            +user_commands
    +cmdline_hist    +jumplist        +persistent_undo +vertsplit
    +cmdline_info    -keymap          +postscript      +virtualedit
    +comments        -langmap         +printer         +visual
    -conceal         +libcall         -profile         +visualextra
    +cryptv          +linebreak       -python          +viminfo
    -cscope          +lispindent      -python3         +vreplace
    +cursorbind      +listcmds        +quickfix        +wildignore
    +cursorshape     +localmap        +reltime         +wildmenu
    +dialog_con_gui  -lua             -rightleft       +windows
    +diff            +menu            -ruby            +writebackup
    +digraphs        +mksession       +scrollbind      +X11
    +dnd             +modify_fname    +signs           -xfontset
    -ebcdic          +mouse           +smartindent     +xim
    -emacs_tags      +mouseshape      -sniff           +xsmp_interact
    +eval            -mouse_dec       +startuptime     +xterm_clipboard
    +ex_extra        +mouse_gpm       +statusline      -xterm_save
    +extra_search    -mouse_jsbterm   -sun_workshop    
    -farsi           -mouse_netterm   +syntax          
       system vimrc file: "$VIM/vimrc"
         user vimrc file: "$HOME/.vimrc"
     2nd user vimrc file: "~/.vim/vimrc"
          user exrc file: "$HOME/.exrc"
      system gvimrc file: "$VIM/gvimrc"
        user gvimrc file: "$HOME/.gvimrc"
    2nd user gvimrc file: "~/.vim/gvimrc"
        system menu file: "$VIMRUNTIME/menu.vim"
      fall-back for $VIM: "/opt/vim/vim74/share/vim"
    Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2  -I/usr/local/include  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
    Linking: gcc   -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype  -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux -lacl -lattr -lgpm -ldl          

I have no `~/.vimrc`

**Comment by egarrulo** [comment]
Maybe you could use `ZQ` instead of `:q!<CR>`?

**Comment by egarrulo** [comment]
Or maybe you could use `man` as a pager, instead of `vim`?  Is this even possible?  Thanks.

**Comment by egarrulo** [comment]
I was wrong!  Apparently, `man` itself uses `less` as a pager.

**Comment by aitjcize** [comment]
There is an option for that. ```cppman -p``` to set pager, check ```cppman -h``` for more info.
I honestly don't know why it doesn't work for your vim. You don't have any other binding in vim that uses <CR>?

**Comment by egarrulo** [comment]
> There is an option for that. cppman -p to set pager, check cppman -h for more info.

That works.  Thank you.

I don't know what could be different in my Vim configuration.  I have no `~/.vimrc`.  There is a `/etc/vim/vimrc` that Vim might be reading, but it doesn't do anything.

**Comment by aitjcize** [comment]
Closing this since no update and can't repo.
