### ISSUE TITLE
XDG Base Directory support

### ISSUE THREAD

**Issue by jwilk** [aitjcize/cppman#45]
It would be cool if cppman followed the [XDG Base Directory Specification](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html).

**Comment by aitjcize** [comment]
Do you mean reading env variable such as XDG_DATA_HOME?
Currently cppman stores it's config to $HOME/.config and data to $HOME/.local/share, which is already confront to the XDG base specification.

**Comment by lantw44** [comment]
I think reading $XDG_CONFIG_HOME and $XDG_DATA_HOME is required by the specification, so this feature is very nice to have.

**Comment by jwilk** [comment]
Yes, I'm mainly interested  in honoring `XDG_*` environment variables.
Although one could argue that cached manpages should by default go to `~/.cache/`, not `~/.local/share/`.
