### ISSUE TITLE
Add to man location of cache

### ISSUE THREAD

**Issue by Yanpas** [aitjcize/cppman#55]
Where does it store cache? Can't find it manually! Please add directory to `man`

**Comment by aitjcize** [comment]
Please use ```cppman -m true``` to enable it.

**Comment by Yanpas** [comment]
@aitjcize I didn't mean that I want to use man utility. I just want to know where cppman stores cache. I can't find it

**Comment by aitjcize** [comment]
It's in $HOME/.local/share/man/

**Comment by Yanpas** [comment]
Thank you!
