### ISSUE TITLE
[Gentoo ebuild] python sqlite USE flag check missing

### ISSUE THREAD

**Issue by PascalRD** [aitjcize/cppman#58]
ebuild:
app-doc/cppman
     Available versions:  (~)0.4.6 {PYTHON_TARGETS="python3_3 python3_4"}
     Installed versions:  0.4.6(11:43:37 AM 04/16/2016)(PYTHON_TARGETS="python3_4 -python3_3")

$ cppman vector
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.4/cppman", line 40, in <module>
    from cppman.main import Cppman
  File "/usr/lib64/python3.4/site-packages/cppman/main.py", line 32, in <module>
    import sqlite3
ImportError: No module named 'sqlite3'

temporary solution:
USE="sqlite" emerge dev-lang/python

**Comment by aitjcize** [comment]
@rindeal Hi Jan, you seems to be the maintainer of the cppman gentoo package. Can you help update the ebuild? Thanks

**Comment by rindeal** [comment]
Fix is on the way, thanks for reporting @PascalRD, though next time please report it on the Gentoo issue tracker.

**Comment by PascalRD** [comment]
Ok, I got it.
