### ISSUE TITLE
Extra dependencies in cppman >= 0.4.8 release

### ISSUE THREAD

**Issue by aitjcize** [aitjcize/cppman#60]
Hi guys,

@czchen @rindeal @eborisch
Thanks for maintaining the cppman package on different platforms. I've just released the 0.4.7 release, and this release requires an extra dependency: 'html5lib'. Can you guys please help adding this dependency to the new package release? Thanks a lot!

AZ

**Comment by aitjcize** [comment]
Please don't push 0.4.7 just yet. I found a regression.

**Comment by aitjcize** [comment]
Regression fixed in 0.4.8 release.

**Comment by czchen** [comment]
Has uploaded to Debian, version 0.4.8-2.

**Comment by aitjcize** [comment]
Thanks!
