### ISSUE TITLE
pager.sh: 61: [: vim: unexpected operator

### ISSUE THREAD

**Issue by erreina** [aitjcize/cppman#64]
Hi, when using a recently installed cppman I am getting this error all the time:

`~$ cppman string`
`/usr/local/lib/python3.4/dist-packages/cppman/lib/pager.sh: 61: [: vim: unexpected operator`
`Vim: Reading from stdin...`

The lines 61 of that file is:

```bash
if [ "$pager_type" == "vim" ]; then
```

but I think it should be:

```bash
if [ "$pager_type" = "vim" ]; then
```

In fact, when removing the extra "`=`" that error disappears.

**Comment by aitjcize** [comment]
This is fixed in the git repo:
https://github.com/aitjcize/cppman/blob/master/cppman/lib/pager.sh#L61

The next release will contain the fix. Thanks!

**Comment by erreina** [comment]
Sorry, I did not realize that it was already fixed. I though I installed directly from github instead of using pip install. Thanks.
