### ISSUE TITLE
A way to support cppman in Emacs

### ISSUE THREAD

**Issue by jethrosun** [aitjcize/cppman#79]
Hi, 

I use Emacs so I am a bit curious that is there a way to integrate `cppman` into Emacs? I mean how can I query and use `cppman` just like linux `man` with a key map. Thx

**Comment by aitjcize** [comment]
You can just set your `PAGER` to emacs, and cppman will open the man pages with emacs.

**Comment by jdees** [comment]
@aitjcize I assume jethrosun did mean it the other way round:
=> "How can I use cppman inside emacs"
(not "How can I use emacs inside cppman")

for example, in Emacs you can type M-x manual-entry "memset" => opens an emacs buffer with the man page of memset.

**Comment by RedJocker** [comment]
hi I was also looking for this and at the end I wrote some emacs wrapper for cppman. 
maybe other emacs users might land here and be interested.

```
(defun cppman (entry)
  "View C++ reference entry using cppman in Emacs, similar to man command.
If called interactively with no argument, uses the symbol at point as default."
  (interactive
   (list (let* ((default (thing-at-point 'symbol t))
                (prompt (if default
                            (format "C++ Reference entry (default %s): " default)
                          "C++ Reference entry: ")))
           (read-string prompt nil nil default))))
  (let ((buffer (get-buffer-create (format "*cppman %s*" entry))))
    (with-current-buffer buffer
      (setq buffer-read-only nil)
      (erase-buffer)
      (call-process-shell-command
       (format "cppman %s | col -b" (shell-quote-argument entry))
       nil (current-buffer))
      (if (zerop (buffer-size))
          (message "No results found for %s" entry)
        (special-mode))
      (setq buffer-read-only t)
      (beginning-of-buffer))
    (unless (zerop (buffer-size))
      (switch-to-buffer buffer))))
```
