### ISSUE TITLE
Unable to use `man` to access cpp man pages

### ISSUE THREAD

**Issue by bbugyi200** [aitjcize/cppman#84]
I ran `cppman -c` and then `cppman -m true` but `man` and `apropos` still cannot find any cpp man pages. I have verified that the man pages are indeed in my filesystem (i.e. the `cppman -c` command worked).

**Comment by aitjcize** [comment]
Can you check the content of `$HOME/.mapath`?

**Comment by bbugyi200** [comment]
Did you mean `$HOME/.manpath`? Here are the contents of that file:

```
MANDATORY_MANPATH	/home/bryan/.local/share/man
```

**Comment by SGSSGene** [comment]
Hello
I couldn't find any documentation, which explains how to make man page use $HOME/.manpath .
But you can set the MANPATH variable:
`export MANPATH="${HOME}/.local/share/man:"` (You probably want to add this line to your .bashrc).

**Comment by bbugyi200** [comment]
@SGSSGene That doesn't resolve this issue for me.

**Comment by Spyros-Ladon** [comment]
Can you run `mandb --create --user-db`? MANPATH and MANDATORY_MANPATH were also necessary for me.

**Comment by SGSSGene** [comment]
Does this issue still exists?

**Comment by bbugyi200** [comment]
I wound up giving up and finding a different solution. I am unable to retest at the moment.

**Comment by kiprasmel** [comment]
I too had this issue (`cppman` does not take into account the `$MANPATH` variable etc.).

So I created this alias in `.bashrc` / `.zshrc`:

```sh
man() {
	/usr/bin/env man $* 2>/dev/null || cppman $*
}
```

:+1:

**Comment by LoxLu250** [comment]
Another possible fix (if it fixes the problem add export line to .bashrc to fix permanently):
```
ln -s {$HOME}/.cache/cppman/cppreference.com {$HOME}/.local/share/man
export MANPATH="${HOME}/.local/share/man:"
mandb
```

Quick dirty fix:
`export MANPATH="${HOME}/.cache/cppman:"`
Works but breaks cppman, "cppman -c", "cppman -r", "cppman std::cout" all return "error: file is not a database"
Fixed by clearing cache
`cppman -C`

**Comment by shirleyquirk** [comment]
for me (Arch Linux) i just had to create the ~/.manpath file and rerun `cppman -m true`

a fix on this end could be to change `update_mandb_path` in util.py to create that file if it doesn't exist, instead of aborting.
