### ISSUE TITLE
feature request: use exit code to indicate if man page was found or not

### ISSUE THREAD

**Issue by tllilleh** [aitjcize/cppman#93]
I would like to be able to call cppman in a script and if no man page was found fallback to something else (like man).  However, it appears as though cppman always has an exit code of 0.  It would be nice to return an error if no man page was found.

**Comment by SGSSGene** [comment]
This is a great idea, I made the PR #94 to add this feature.

**Comment by aitjcize** [comment]
merged, thanks @SGSSGene !
