### ISSUE TITLE
cppman override return error

### ISSUE THREAD

**Issue by lidaobing** [aitjcize/cppman#96]
```
$ cppman -s cppreference.com
Source set to `cppreference.com'.
$ cppman override
error: bad escape \e at position 0
$ cppman --version
/usr/local/bin/cppman Ver 0.4.9
```

**Comment by SGSSGene** [comment]
Hey

this problem is already solved in the current `master` branch. See #86

**Comment by lidaobing** [comment]
merged into #86.

@SGSSGene any plan for a new release?

**Comment by SGSSGene** [comment]
I actually don't know the release process. This is a question for @aitjcize  again :-)

**Comment by aitjcize** [comment]
let me do that now
