### ISSUE TITLE
"cppman -f" failed

### ISSUE THREAD

**Issue by lidaobing** [aitjcize/cppman#97]
the git master version cppman

```
$ cppman -f "final specifier (since C++11)"
error: multiple repeat at position 26
```

**Comment by SGSSGene** [comment]
Oh! yes this is a bug. This shouldn't behave this way.
Also `cppman -f "final specifier"` shows to many entries.

Feel free (and anyone else), to fix this. I currently am a little short on time. It will take me some time to come and tackle this "edge case" bug.

**Comment by SGSSGene** [comment]
This is now fixed.
